/**
 * CLIProxy listen host — generator tests.
 *
 * Covers:
 *   1. A fresh config binds CLIProxy to 127.0.0.1, not every interface.
 *   2. CCS_CLIPROXY_HOST overrides the default (the Docker images set 0.0.0.0);
 *      a blank value counts as unset.
 *   3. Regeneration keeps a host the user set, including "" (all interfaces),
 *      and adds the loopback host to older generated configs, which have no host line.
 *   4. CCS_CLIPROXY_HOST wins over a host in the existing config.
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { afterEach, beforeEach, describe, expect, it } from 'bun:test';

function createTestHome(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ccs-cliproxy-host-test-'));
  const ccsDir = path.join(dir, '.ccs');
  fs.mkdirSync(ccsDir, { recursive: true });
  fs.writeFileSync(path.join(ccsDir, 'config.yaml'), 'version: 1\n', 'utf8');
  return dir;
}

function hostLines(content: string): string[] {
  return content.split('\n').filter((line) => line.startsWith('host:'));
}

describe('CLIProxy listen host — generator', () => {
  let tempHome: string;
  let originalEnv: Record<string, string | undefined>;

  beforeEach(() => {
    tempHome = createTestHome();
    originalEnv = {
      CCS_DIR: process.env.CCS_DIR,
      CCS_HOME: process.env.CCS_HOME,
      CCS_CLIPROXY_HOST: process.env.CCS_CLIPROXY_HOST,
    };
    delete process.env.CCS_DIR;
    delete process.env.CCS_CLIPROXY_HOST;
    process.env.CCS_HOME = tempHome;
  });

  afterEach(() => {
    for (const [key, value] of Object.entries(originalEnv)) {
      if (value !== undefined) {
        process.env[key] = value;
      } else {
        delete process.env[key];
      }
    }
    fs.rmSync(tempHome, { recursive: true, force: true });
  });

  function paths(tag: string): { configPath: string; authDir: string } {
    const cliproxyDir = path.join(tempHome, '.ccs', 'cliproxy');
    fs.mkdirSync(cliproxyDir, { recursive: true });
    return {
      configPath: path.join(cliproxyDir, `config-${tag}.yaml`),
      authDir: path.join(cliproxyDir, 'auth'),
    };
  }

  it('a fresh config binds CLIProxy to 127.0.0.1', async () => {
    const { generateConfig, CLIPROXY_DEFAULT_HOST } = await import(
      `../config/generator?hostgen1=${Date.now()}`
    );

    const configPath = generateConfig('gemini', 8317);

    expect(configPath.startsWith(tempHome)).toBe(true);
    const content = fs.readFileSync(configPath, 'utf-8');
    expect(CLIPROXY_DEFAULT_HOST).toBe('127.0.0.1');
    expect(hostLines(content)).toEqual(['host: "127.0.0.1"']);
    // host sits with port in the top-level server settings
    expect(content).toContain('host: "127.0.0.1"\nport: 8317\n');
  });

  it('CCS_CLIPROXY_HOST overrides the default', async () => {
    process.env.CCS_CLIPROXY_HOST = '0.0.0.0';
    const { regenerateConfig } = await import(`../config/generator?hostgen2=${Date.now()}`);
    const { configPath, authDir } = paths('env');

    regenerateConfig(8317, { configPath, authDir });

    expect(hostLines(fs.readFileSync(configPath, 'utf-8'))).toEqual(['host: "0.0.0.0"']);
  });

  it('a blank CCS_CLIPROXY_HOST counts as unset', async () => {
    process.env.CCS_CLIPROXY_HOST = '  ';
    const { regenerateConfig } = await import(`../config/generator?hostgen3=${Date.now()}`);
    const { configPath, authDir } = paths('blank-env');

    regenerateConfig(8317, { configPath, authDir });

    expect(hostLines(fs.readFileSync(configPath, 'utf-8'))).toEqual(['host: "127.0.0.1"']);
  });

  it('regeneration adds the loopback host to an older config without one', async () => {
    const { regenerateConfig } = await import(`../config/generator?hostgen4=${Date.now()}`);
    const { configPath, authDir } = paths('no-host');
    fs.writeFileSync(
      configPath,
      '# CLIProxyAPI config generated by CCS v21\nport: 8317\ndebug: false\n',
      'utf8'
    );

    regenerateConfig(8317, { configPath, authDir });

    expect(hostLines(fs.readFileSync(configPath, 'utf-8'))).toEqual(['host: "127.0.0.1"']);
  });

  it('regeneration keeps a host the user set', async () => {
    const { regenerateConfig } = await import(`../config/generator?hostgen5=${Date.now()}`);
    const cases: Array<[string, string]> = [
      ['host: ""', 'host: ""'],
      ["host: ''", 'host: ""'],
      ['host:', 'host: ""'],
      ['host: 192.168.1.20 # LAN', 'host: "192.168.1.20"'],
      ['host: "10.0.0.5"', 'host: "10.0.0.5"'],
    ];

    for (const [index, [existingLine, expectedLine]] of cases.entries()) {
      const { configPath, authDir } = paths(`user-host-${index}`);
      fs.writeFileSync(
        configPath,
        `# CLIProxyAPI config generated by CCS v21\n${existingLine}\nport: 8317\ndebug: false\n`,
        'utf8'
      );

      regenerateConfig(8317, { configPath, authDir });

      expect(hostLines(fs.readFileSync(configPath, 'utf-8'))).toEqual([expectedLine]);
    }
  });

  it('CCS_CLIPROXY_HOST wins over a host in the existing config', async () => {
    process.env.CCS_CLIPROXY_HOST = '0.0.0.0';
    const { regenerateConfig } = await import(`../config/generator?hostgen6=${Date.now()}`);
    const { configPath, authDir } = paths('env-over-existing');
    fs.writeFileSync(
      configPath,
      '# CLIProxyAPI config generated by CCS v21\nhost: "127.0.0.1"\nport: 8317\ndebug: false\n',
      'utf8'
    );

    regenerateConfig(8317, { configPath, authDir });

    expect(hostLines(fs.readFileSync(configPath, 'utf-8'))).toEqual(['host: "0.0.0.0"']);
  });

  it('nested host keys in other sections are not taken as the listen host', async () => {
    const { regenerateConfig } = await import(`../config/generator?hostgen7=${Date.now()}`);
    const { configPath, authDir } = paths('nested-host');
    fs.writeFileSync(
      configPath,
      '# CLIProxyAPI config generated by CCS v21\nport: 8317\nsome-section:\n  host: "0.0.0.0"\n',
      'utf8'
    );

    regenerateConfig(8317, { configPath, authDir });

    expect(hostLines(fs.readFileSync(configPath, 'utf-8'))).toEqual(['host: "127.0.0.1"']);
  });
});
