/**
 * CLIProxy config regeneration on a CLIProxyAPI v8-layout config.yaml.
 *
 * CLIProxyAPI v8 migrates config.yaml to a nested layout and marks it with
 * `config-version:`. Regeneration writes CCS's legacy layout, which the v8 loader
 * still accepts, so it must:
 *   1. keep the v8 sections CCS doesn't generate (upstream, the api-keys upstream map,
 *      config-version), including their comments;
 *   2. read port, client keys and aliases from their v8 paths;
 *   3. move CCS's client keys to access.api-keys, because v8 uses top-level api-keys
 *      for the upstream key map;
 *   4. stay stable when run again on its own output, and leave legacy configs alone.
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as yaml from 'js-yaml';
import { afterEach, beforeEach, describe, expect, it } from 'bun:test';

const V8_CONFIG = `# CLIProxyAPI config generated by CCS v21
# Generated: 2026-07-30T01:42:05.416Z
quota-exceeded:
    switch-project: true
    switch-preview-model: true
routing:
    strategy: round-robin
observability:
    logs:
        request-log: false
        debug: false
        logging-to-file: false
    usage:
        usage-statistics-enabled: true
access:
    # API keys for CCS and user-added external requests
    api-keys:
        - ccs-internal-managed
        - user-added-key
server:
    port: 8318
management:
    allow-remote: true
    secret-key: test-secret
    disable-control-panel: false
oauth:
    auth-dir: /tmp/old-auth
    model-alias:
        antigravity:
            - name: user-model
              alias: user-alias
              fork: true
upstream:
    # Claude upstream overrides
    claude:
        base-url: https://claude-upstream.example.com
        header-defaults:
            user-agent: test-agent/1.0
api-keys:
    claude:
        - name: claude-1
          base-url: https://api.example.com
          proxy-url: socks5://127.0.0.1:1080
          models:
            - name: claude-test-model
              alias: test-alias
          keys:
            - api-key: sk-test-upstream
config-version: 8
`;

function createTestHome(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ccs-cliproxy-v8-test-'));
  const ccsDir = path.join(dir, '.ccs');
  fs.mkdirSync(ccsDir, { recursive: true });
  fs.writeFileSync(path.join(ccsDir, 'config.yaml'), 'version: 1\n', 'utf8');
  return dir;
}

function load(content: string): Record<string, unknown> {
  return yaml.load(content) as Record<string, unknown>;
}

describe('CLIProxy config regeneration — v8 layout', () => {
  let tempHome: string;
  let originalEnv: Record<string, string | undefined>;

  beforeEach(() => {
    tempHome = createTestHome();
    originalEnv = { CCS_DIR: process.env.CCS_DIR, CCS_HOME: process.env.CCS_HOME };
    delete process.env.CCS_DIR;
    process.env.CCS_HOME = tempHome;
  });

  afterEach(() => {
    for (const [key, value] of Object.entries(originalEnv)) {
      if (value !== undefined) {
        process.env[key] = value;
      } else {
        delete process.env[key];
      }
    }
    fs.rmSync(tempHome, { recursive: true, force: true });
  });

  async function regenerateFrom(tag: string, existing: string): Promise<string> {
    const { regenerateConfig } = await import(`../config/generator?v8gen-${tag}=${Date.now()}`);
    const cliproxyDir = path.join(tempHome, '.ccs', 'cliproxy');
    fs.mkdirSync(cliproxyDir, { recursive: true });
    const configPath = path.join(cliproxyDir, `config-${tag}.yaml`);
    fs.writeFileSync(configPath, existing, 'utf8');
    regenerateConfig(8317, { configPath, authDir: path.join(cliproxyDir, 'auth') });
    return fs.readFileSync(configPath, 'utf-8');
  }

  it('keeps the v8 sections CCS does not generate, with their comments', async () => {
    const before = load(V8_CONFIG);
    const content = await regenerateFrom('keep', V8_CONFIG);
    const after = load(content);

    expect(after.upstream).toEqual(before.upstream);
    expect(after['api-keys']).toEqual(before['api-keys']);
    expect(after['config-version']).toBe(8);
    expect(content).toContain('# Claude upstream overrides');
  });

  it('reads port, client keys and aliases from their v8 paths', async () => {
    const after = load(await regenerateFrom('read', V8_CONFIG));

    expect(after.port).toBe(8318);
    const access = after.access as Record<string, unknown>;
    expect(access['api-keys']).toContain('user-added-key');
    const aliases = after['oauth-model-alias'] as Record<string, unknown[]>;
    expect(aliases.antigravity).toContainEqual({
      name: 'user-model',
      alias: 'user-alias',
      fork: true,
    });
  });

  it('writes client keys to access.api-keys and regenerates the v8 roots it manages', async () => {
    const after = load(await regenerateFrom('roots', V8_CONFIG));

    expect(Array.isArray(after['api-keys'])).toBe(false);
    for (const root of ['server', 'observability', 'management', 'oauth']) {
      expect(after[root]).toBeUndefined();
    }
  });

  it('is stable when run again on its own output', async () => {
    const first = await regenerateFrom('stable-1', V8_CONFIG);
    const second = await regenerateFrom('stable-2', first);

    expect(load(second)).toEqual(load(first));
  });

  it('drops a stale conditionally generated key', async () => {
    const after = load(await regenerateFrom('stale', `${V8_CONFIG}max-retry-credentials: 3\n`));

    expect(after['max-retry-credentials']).toBeUndefined();
    expect(after.upstream).toBeDefined();
  });

  it('keeps client keys top-level when there is no v8 upstream key map', async () => {
    const withoutKeyMap = V8_CONFIG.replace(/^api-keys:\n(?:[ \t].*\n)*/m, '');
    const after = load(await regenerateFrom('no-map', withoutKeyMap));

    expect(after['api-keys']).toContain('user-added-key');
    expect(after.access).toBeUndefined();
    expect(after.upstream).toBeDefined();
  });

  it('leaves legacy configs in the legacy layout', async () => {
    const after = load(
      await regenerateFrom(
        'legacy',
        '# CLIProxyAPI config generated by CCS v21\nport: 8318\napi-keys:\n  - "user-added-key"\n'
      )
    );

    expect(after.port).toBe(8318);
    expect(after['api-keys']).toContain('user-added-key');
    expect(after.access).toBeUndefined();
    expect(after['config-version']).toBeUndefined();
  });

  it('falls back to legacy handling when a v8 config cannot be parsed', async () => {
    const after = load(await regenerateFrom('broken', `${V8_CONFIG}upstream: [unclosed\n`));

    expect(Array.isArray(after['api-keys'])).toBe(true);
    expect(after.upstream).toBeUndefined();
  });
});
